AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'db/*'
    - 'db/migrate/*'
    - 'config/*'
    - 'lib/*'
    - 'spec/*_helper.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
