AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'db/*'
    - 'config/*'
    - 'lib/*'
    - 'spec/*_helper.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
